config/routes.rb
Rails.application.routes.draw do
  root to:'home#index'
  devise_for :users, :controllers => {
  :registrations => 'users/registrations',
  :sessions => 'users/sessions'
  }

  devise_scope :user do
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end
  resources :users
  resources :is_opens
  resources :reviews
  resources :releases
  resources :projects
  resources :team_projects
  resources :teams
  resources :memos
  resources :messages
  resources :members
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/is_open.rb
class IsOpen < ApplicationRecord
end

app/models/member.rb
class Member < ApplicationRecord
end

app/models/memo.rb
class Memo < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/release.rb
class Release < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/team.rb
class Team < ApplicationRecord
end

app/models/team_project.rb
class TeamProject < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/team_projects_controller.rb
class TeamProjectsController < ApplicationController
  before_action :set_team_project, only: [:show, :edit, :update, :destroy]

  # GET /team_projects
  # GET /team_projects.json
  def index
    @team_projects = TeamProject.all
  end

  # GET /team_projects/1
  # GET /team_projects/1.json
  def show
  end

  # GET /team_projects/new
  def new
    @team_project = TeamProject.new
  end

  # GET /team_projects/1/edit
  def edit
  end

  # POST /team_projects
  # POST /team_projects.json
  def create
    @team_project = TeamProject.new(team_project_params)

    respond_to do |format|
      if @team_project.save
        format.html { redirect_to @team_project, notice: 'Team project was successfully created.' }
        format.json { render :show, status: :created, location: @team_project }
      else
        format.html { render :new }
        format.json { render json: @team_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /team_projects/1
  # PATCH/PUT /team_projects/1.json
  def update
    respond_to do |format|
      if @team_project.update(team_project_params)
        format.html { redirect_to @team_project, notice: 'Team project was successfully updated.' }
        format.json { render :show, status: :ok, location: @team_project }
      else
        format.html { render :edit }
        format.json { render json: @team_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /team_projects/1
  # DELETE /team_projects/1.json
  def destroy
    @team_project.destroy
    respond_to do |format|
      format.html { redirect_to team_projects_url, notice: 'Team project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team_project
      @team_project = TeamProject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_project_params
      params.require(:team_project).permit(:team_id, :project_id, :icon, :is_public, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/is_opens_helper.rb
module IsOpensHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/releases_helper.rb
module ReleasesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/team_projects_helper.rb
module TeamProjectsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/team_projects/_form.html.erb
<%= form_with(model: team_project, local: true) do |form| %>
  <% if team_project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(team_project.errors.count, "error") %> prohibited this team_project from being saved:</h2>

      <ul>
      <% team_project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :team_id %>
    <%= form.number_field :team_id %>
  </div>

  <div class="field">
    <%= form.label :project_id %>
    <%= form.number_field :project_id %>
  </div>

  <div class="field">
    <%= form.label :icon %>
    <%= form.text_field :icon %>
  </div>

  <div class="field">
    <%= form.label :is_public %>
    <%= form.number_field :is_public %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_field :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/team_projects/edit.html.erb
<h1>Editing Team Project</h1>

<%= render 'form', team_project: @team_project %>

<%= link_to 'Show', @team_project %> |
<%= link_to 'Back', team_projects_path %>

app/views/team_projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Team Projects</h1>

<table>
  <thead>
    <tr>
      <th>Team</th>
      <th>Project</th>
      <th>Icon</th>
      <th>Is public</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @team_projects.each do |team_project| %>
      <tr>
        <td><%= team_project.team_id %></td>
        <td><%= team_project.project_id %></td>
        <td><%= team_project.icon %></td>
        <td><%= team_project.is_public %></td>
        <td><%= team_project.comment %></td>
        <td><%= link_to 'Show', team_project %></td>
        <td><%= link_to 'Edit', edit_team_project_path(team_project) %></td>
        <td><%= link_to 'Destroy', team_project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Team Project', new_team_project_path %>

app/views/team_projects/new.html.erb
<h1>New Team Project</h1>

<%= render 'form', team_project: @team_project %>

<%= link_to 'Back', team_projects_path %>

app/views/team_projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Team:</strong>
  <%= @team_project.team_id %>
</p>

<p>
  <strong>Project:</strong>
  <%= @team_project.project_id %>
</p>

<p>
  <strong>Icon:</strong>
  <%= @team_project.icon %>
</p>

<p>
  <strong>Is public:</strong>
  <%= @team_project.is_public %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @team_project.comment %>
</p>

<%= link_to 'Edit', edit_team_project_path(@team_project) %> |
<%= link_to 'Back', team_projects_path %>