config/routes.rb
Rails.application.routes.draw do
  root to:'home#index'
  devise_for :users, :controllers => {
  :registrations => 'users/registrations',
  :sessions => 'users/sessions'
  }

  devise_scope :user do
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end
  resources :users
  resources :is_opens
  resources :reviews
  resources :releases
  resources :projects
  resources :team_projects
  resources :teams
  resources :memos
  resources :messages
  resources :members
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/is_open.rb
class IsOpen < ApplicationRecord
end

app/models/member.rb
class Member < ApplicationRecord
end

app/models/memo.rb
class Memo < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/release.rb
class Release < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/team.rb
class Team < ApplicationRecord
end

app/models/team_project.rb
class TeamProject < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/is_opens_controller.rb
class IsOpensController < ApplicationController
  before_action :set_is_open, only: [:show, :edit, :update, :destroy]

  # GET /is_opens
  # GET /is_opens.json
  def index
    @is_opens = IsOpen.all
  end

  # GET /is_opens/1
  # GET /is_opens/1.json
  def show
  end

  # GET /is_opens/new
  def new
    @is_open = IsOpen.new
  end

  # GET /is_opens/1/edit
  def edit
  end

  # POST /is_opens
  # POST /is_opens.json
  def create
    @is_open = IsOpen.new(is_open_params)

    respond_to do |format|
      if @is_open.save
        format.html { redirect_to @is_open, notice: 'Is open was successfully created.' }
        format.json { render :show, status: :created, location: @is_open }
      else
        format.html { render :new }
        format.json { render json: @is_open.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /is_opens/1
  # PATCH/PUT /is_opens/1.json
  def update
    respond_to do |format|
      if @is_open.update(is_open_params)
        format.html { redirect_to @is_open, notice: 'Is open was successfully updated.' }
        format.json { render :show, status: :ok, location: @is_open }
      else
        format.html { render :edit }
        format.json { render json: @is_open.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /is_opens/1
  # DELETE /is_opens/1.json
  def destroy
    @is_open.destroy
    respond_to do |format|
      format.html { redirect_to is_opens_url, notice: 'Is open was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_is_open
      @is_open = IsOpen.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def is_open_params
      params.require(:is_open).permit(:user_id, :age, :join_team, :join_project, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/is_opens_helper.rb
module IsOpensHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/releases_helper.rb
module ReleasesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/is_opens/_form.html.erb
<%= form_with(model: is_open, local: true) do |form| %>
  <% if is_open.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(is_open.errors.count, "error") %> prohibited this is_open from being saved:</h2>

      <ul>
      <% is_open.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :join_team %>
    <%= form.number_field :join_team %>
  </div>

  <div class="field">
    <%= form.label :join_project %>
    <%= form.number_field :join_project %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.number_field :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/is_opens/edit.html.erb
<h1>Editing Is Open</h1>

<%= render 'form', is_open: @is_open %>

<%= link_to 'Show', @is_open %> |
<%= link_to 'Back', is_opens_path %>

app/views/is_opens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Is Opens</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Age</th>
      <th>Join team</th>
      <th>Join project</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @is_opens.each do |is_open| %>
      <tr>
        <td><%= is_open.user_id %></td>
        <td><%= is_open.age %></td>
        <td><%= is_open.join_team %></td>
        <td><%= is_open.join_project %></td>
        <td><%= is_open.comment %></td>
        <td><%= link_to 'Show', is_open %></td>
        <td><%= link_to 'Edit', edit_is_open_path(is_open) %></td>
        <td><%= link_to 'Destroy', is_open, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Is Open', new_is_open_path %>

app/views/is_opens/new.html.erb
<h1>New Is Open</h1>

<%= render 'form', is_open: @is_open %>

<%= link_to 'Back', is_opens_path %>

app/views/is_opens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @is_open.user_id %>
</p>

<p>
  <strong>Age:</strong>
  <%= @is_open.age %>
</p>

<p>
  <strong>Join team:</strong>
  <%= @is_open.join_team %>
</p>

<p>
  <strong>Join project:</strong>
  <%= @is_open.join_project %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @is_open.comment %>
</p>

<%= link_to 'Edit', edit_is_open_path(@is_open) %> |
<%= link_to 'Back', is_opens_path %>