config/routes.rb
Rails.application.routes.draw do
  root to:'home#index'
  devise_for :users, :controllers => {
  :registrations => 'users/registrations',
  :sessions => 'users/sessions'
  }

  devise_scope :user do
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end
  resources :users
  resources :is_opens
  resources :reviews
  resources :releases
  resources :projects
  resources :team_projects
  resources :teams
  resources :memos
  resources :messages
  resources :members
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/is_open.rb
class IsOpen < ApplicationRecord
end

app/models/member.rb
class Member < ApplicationRecord
end

app/models/memo.rb
class Memo < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/release.rb
class Release < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/team.rb
class Team < ApplicationRecord
end

app/models/team_project.rb
class TeamProject < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :set_memo, only: [:show, :edit, :update, :destroy]

  # GET /memos
  # GET /memos.json
  def index
    @memos = Memo.all
  end

  # GET /memos/1
  # GET /memos/1.json
  def show
  end

  # GET /memos/new
  def new
    @memo = Memo.new
  end

  # GET /memos/1/edit
  def edit
  end

  # POST /memos
  # POST /memos.json
  def create
    @memo = Memo.new(memo_params)

    respond_to do |format|
      if @memo.save
        format.html { redirect_to @memo, notice: 'Memo was successfully created.' }
        format.json { render :show, status: :created, location: @memo }
      else
        format.html { render :new }
        format.json { render json: @memo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memos/1
  # PATCH/PUT /memos/1.json
  def update
    respond_to do |format|
      if @memo.update(memo_params)
        format.html { redirect_to @memo, notice: 'Memo was successfully updated.' }
        format.json { render :show, status: :ok, location: @memo }
      else
        format.html { render :edit }
        format.json { render json: @memo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memos/1
  # DELETE /memos/1.json
  def destroy
    @memo.destroy
    respond_to do |format|
      format.html { redirect_to memos_url, notice: 'Memo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_memo
      @memo = Memo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def memo_params
      params.require(:memo).permit(:is_team, :team_id, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/is_opens_helper.rb
module IsOpensHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/releases_helper.rb
module ReleasesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/memos/_form.html.erb
<%= form_with(model: memo, local: true) do |form| %>
  <% if memo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(memo.errors.count, "error") %> prohibited this memo from being saved:</h2>

      <ul>
      <% memo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :is_team %>
    <%= form.text_field :is_team %>
  </div>

  <div class="field">
    <%= form.label :team_id %>
    <%= form.text_field :team_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/memos/edit.html.erb
<h1>Editing Memo</h1>

<%= render 'form', memo: @memo %>

<%= link_to 'Show', @memo %> |
<%= link_to 'Back', memos_path %>

app/views/memos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Memos</h1>

<table>
  <thead>
    <tr>
      <th>Is team</th>
      <th>Team</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memos.each do |memo| %>
      <tr>
        <td><%= memo.is_team %></td>
        <td><%= memo.team_id %></td>
        <td><%= memo.user_id %></td>
        <td><%= link_to 'Show', memo %></td>
        <td><%= link_to 'Edit', edit_memo_path(memo) %></td>
        <td><%= link_to 'Destroy', memo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Memo', new_memo_path %>

app/views/memos/new.html.erb
<h1>New Memo</h1>

<%= render 'form', memo: @memo %>

<%= link_to 'Back', memos_path %>

app/views/memos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Is team:</strong>
  <%= @memo.is_team %>
</p>

<p>
  <strong>Team:</strong>
  <%= @memo.team_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @memo.user_id %>
</p>

<%= link_to 'Edit', edit_memo_path(@memo) %> |
<%= link_to 'Back', memos_path %>